"""extend analysis persistence fields

Revision ID: b2acccb169f6
Revises: 6774ed234ffb
Create Date: 2026-05-28 11:40:31.329343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2acccb169f6'
down_revision: Union[str, Sequence[str], None] = '6774ed234ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('findings_count', sa.Integer(), nullable=False))
    op.add_column('analyses', sa.Column('test_recommendations_count', sa.Integer(), nullable=False))
    op.add_column('analyses', sa.Column('deterministic_score', sa.Integer(), nullable=True))
    op.add_column('analyses', sa.Column('ai_adjustment', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_analyses_created_at'), 'analyses', ['created_at'], unique=False)
    op.create_unique_constraint('uq_analysis_repo_pr_head_created', 'analyses', ['repository_id', 'pr_number', 'head_branch', 'created_at'])
    op.add_column('findings', sa.Column('source', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'source')
    op.drop_constraint('uq_analysis_repo_pr_head_created', 'analyses', type_='unique')
    op.drop_index(op.f('ix_analyses_created_at'), table_name='analyses')
    op.drop_column('analyses', 'ai_adjustment')
    op.drop_column('analyses', 'deterministic_score')
    op.drop_column('analyses', 'test_recommendations_count')
    op.drop_column('analyses', 'findings_count')
    # ### end Alembic commands ###
