import json

from pr_sentinel.core.enums import FindingCategory, RiskBand, Severity
from pr_sentinel.core.models import AnalysisResult, Finding, PullRequestInfo, RiskScore
from pr_sentinel.reports.json_report import JsonReportGenerator
from pr_sentinel.reports.markdown import MarkdownReportGenerator


def _sample_result() -> AnalysisResult:
    pr = PullRequestInfo(
        repo_full_name="example/repo",
        pr_number=12,
        title="Risky auth change",
        author="ivan",
        base_branch="main",
        head_branch="feature/auth",
        html_url="https://github.com/example/repo/pull/12",
        changed_files=[],
    )

    finding = Finding(
        rule_id="AUTH_001_PERMISSION_CHECK_REMOVED",
        title="Permission check removed",
        category=FindingCategory.AUTH,
        severity=Severity.HIGH,
        file_path="src/AuthFilter.java",
        line_number=42,
        message="A permission check was removed.",
        evidence="if (!hasPermission(user)) throw new ForbiddenException();",
        recommendation="Verify authorization and add negative tests.",
        confidence=0.8,
    )

    risk_score = RiskScore(
        score=32,
        band=RiskBand.MEDIUM,
        breakdown={"AUTH": 32},
        deterministic_score=32,
        ai_adjustment=0,
        ai_adjustment_reasons=[],
    )

    return AnalysisResult(
        pr=pr,
        findings=[finding],
        test_recommendations=[],
        risk_score=risk_score,
        summary=None,
    )


def test_json_report_generator_outputs_valid_json() -> None:
    result = _sample_result()

    report = JsonReportGenerator().generate_json(result)
    parsed = json.loads(report)

    assert parsed["pr"]["repo_full_name"] == "example/repo"
    assert parsed["findings"][0]["rule_id"] == "AUTH_001_PERMISSION_CHECK_REMOVED"
    assert parsed["risk_score"]["score"] == 32


def test_markdown_report_generator_outputs_expected_sections() -> None:
    result = _sample_result()

    report = MarkdownReportGenerator().generate(result)

    assert "# PRSentinel Risk Report" in report
    assert "## Risk Summary" in report
    assert "## Findings" in report
    assert "Permission check removed" in report
    assert "AUTH_001_PERMISSION_CHECK_REMOVED" in report
    assert "Generated by PRSentinel" in report